# Generated by Django 4.2.23 on 2025-08-06 04:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_features', models.JSONField()),
                ('invoice_features', models.JSONField()),
                ('is_match', models.BooleanField()),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='core.company')),
            ],
            options={
                'db_table': 'ml_engine_trainingdata',
                'indexes': [models.Index(fields=['company', 'is_match'], name='ml_engine_t_company_9f1a76_idx'), models.Index(fields=['created_at'], name='ml_engine_t_created_5f9bbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField()),
                ('invoice_id', models.UUIDField()),
                ('model_version', models.CharField(max_length=50)),
                ('prediction_score', models.FloatField()),
                ('features_used', models.JSONField()),
                ('prediction_metadata', models.JSONField(default=dict)),
                ('actual_outcome', models.BooleanField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'ml_engine_modelprediction',
                'indexes': [models.Index(fields=['company', 'transaction_id'], name='ml_engine_m_company_864dc0_idx'), models.Index(fields=['prediction_score'], name='ml_engine_m_predict_a8700b_idx'), models.Index(fields=['model_version'], name='ml_engine_m_model_v_0c5780_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureExtraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_type', models.CharField(choices=[('text', 'Text Features'), ('numeric', 'Numeric Features'), ('categorical', 'Categorical Features'), ('temporal', 'Temporal Features')], max_length=20)),
                ('extraction_config', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('importance_score', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'ml_engine_featureextraction',
                'unique_together': {('company', 'feature_name')},
            },
        ),
    ]
